services:
  - type: web
    name: bp-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn model.api:app --host 0.0.0.0 --port 10000
    plan: free
